---
- name: Create instances
  os_server:
    cloud: "{{ __server.cloud_name | default('openstack') }}"
    name: "{{ __server.instance_name }}"
    image: "{{ __server.image }}"
    key_name: "{{ __server.key | default('ansible_ssh_key') }}"
    flavor: "{{ __server.flavor }}"
    security_groups: "{{ __server.security_group_name }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: "{{ __server.nic }}"
    meta: "group={{ __server.group }},deployment_name={{ __server.deployment }}"
    userdata: |
      #!/bin/bash
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  loop: "{{ openstack_servers }}"
  loop_control:
    loop_var: __server
    
- name: Add floating IP to instance
  os_floating_ip:
    cloud: "{{ __server.cloud_name | default('openstack') }}"
    state: present
    reuse: yes
    server: "{{ __server.instance_name }}"
    network: "{{ __server.network }}"
    wait: true
    timeout: 200
  loop: "{{ openstack_servers }}"
  loop_control:
    loop_var: __server
